@startuml
title Simplified Create Stock Input Class Diagram
hide empty members

class "UI Service" as UIService

class StockInputController {
  + CreateStockInput(vm: StockInputCreateVM)
}

interface IStockInputService {
  + CreateStockInput(vm: StockInputCreateVM)
}


package "Database Entities" {
    entity StockInput
    entity StockInputDetail
    entity Inventory
}

UIService ..> StockInputController : calls
StockInputController --> IStockInputService


' Logic relationships
IStockInputService --> StockInput : creates
IStockInputService --> StockInputDetail : creates
IStockInputService --> Inventory : updates quantity

@enduml